---
title: "Figure 2"
author: HA Hill
project: MCL MATCH
output:
  pdf_document: default
  html_document:default
  word_document: default
---

```{r}
library(tidyverse)
library(EnhancedVolcano)
library(ComplexHeatmap)

```

```{r}
#Visualization of DEG using a volcano plot

Supplementary_Tables <- read_excel("~/Desktop/MATCH_npj_PO/Supplementary_Tables.xlsx", 
 sheet = "STable6_Gene_counts_FC")

Supplementary_Tables_1$log2FoldChange_opposite <- (Supplementary_Tables_1$log2FoldChange)*(-1)
```

```{r}
Supplementary_Tables$pvalue <- as.numeric(Supplementary_Tables$pvalue)

  e <- EnhancedVolcano(Supplementary_Tables,
    lab = Supplementary_Tables$upperSymbol,
    x = 'log2FoldChange',
    y = 'pvalue',
    title = 'Non Responders vs Responders',
    subtitle = "Differential Expression",
    pCutoff = 0.0114275,
    FCcutoff = 1,
   pointSize = 1.5,
    labSize = 3.0,
    labCol = 'black',
    labFace = 'bold',
    boxedLabels = FALSE,
    colAlpha = 4/5,
    legendPosition = 'right',
    legendLabSize = 10,
    legendIconSize = 3.0,
    drawConnectors = TRUE,
    widthConnectors = 0.5,
    colConnectors = 'black')
  
  plot <- e + ggplot2::coord_cartesian(xlim=c(-2.75, 2.75), ylim=c(0,5))
```

```{r}
pdf(file = "Volcano_NResp_Resp.pdf", height=9, width=9)

plot

dev.off()
```


#Heatmap of DGES

```{r}
m <- MCL_heatmap %>% select(1:42) 

m <- sapply(m, as.numeric)

m <- t(m)

m <- as.matrix(m)

```

```{r}
anno <- MCL_heatmap %>% select(43:47)
```

```{r}
BTKi = anno$Response
Sample = anno$Tissue
Time = anno$Time
Sex = anno$Sex
```

```{r}
ha = HeatmapAnnotation(BTKi=BTKi, Sample = Sample, Time=Time, Sex = Sex, col=list('BTKi'=c('Non-responder'= "darkblue",'Responder'="darkgreen"),
  'Sample'=c('Apheresis'="orange",'LN'="yellow",'BM'="blue",'PB'="red","Other"="gray"),
  'Sex'=c('female'="pink",'male'="lightblue"),
  'Time'=c('Naiive'="#67a9cf",'Relapsed'="violet","Treatment"="darkred")), which = "column", annotation_name_gp = gpar(fontsize = 8))
```


```{r}
pdf(file="DEG_heatmap_MCL.pdf", height=11, width=8)

heat <- Heatmap(m, heatmap_legend_param = list(title = "Expression"), top_annotation = ha, row_names_side = 'left', row_km = 4, row_names_gp = gpar(fontsize = 9, fontface = "italic"), column_names_gp = gpar(fontsize = 9), cluster_rows = T, cluster_columns = F, column_split = BTKi)

plot(heat)

dev.off()
```

