---
title: "MATCH GSEA"
output: html_notebook
---
#Load packages
```{r}
library(tidyverse)
library(readr)
library(readxl)
library(GSVA)
library(GSEABase)
library(GSVAdata)
```
#Files are read into R environment as dataframes

```{r}
MCL_MATCH_new_normalizedCountsWithAnnotations <- read_delim("~/Desktop/MATCH_update/MCL_MATCH_3_normalizedCountsWithAnnotations.tsv", 
delim = "\t", escape_double = FALSE, 
trim_ws = TRUE)

Tumor_360_Gene_Sets_gmt <- read_excel("~/Desktop/MATCH_update/Tumor_360_Gene_Sets.gmt.xlsx", 
    sheet = "gene_set_for_GSEA")


```

```{r}

#Normalized counts file
MCL <- (MATCH_new_normalizedCountsWithAnnotations)
MCL<- as.matrix(data.frame(MCL[,-1:-4], row.names = MCL$Symbol))

#Gene Set file

T360 <- Tumor_360_Gene_Sets_gmt


#GSVA algorithm

GSVA <-gsva(MCL,T360)
GSVA_MATCH <- gsva(MCL,MATCH)


GSVA_bio <-gsva(MCL,biocarta)

GSVA_kegg <-gsva(MCL,kegg)

GSVA_hallmark <- gsva(MCL, hallmark)

#Use different algorithms

SSGSEA <-gsva(MCL,T360, method=c("ssgsea"))

z_score <-gsva(MCL,T360, method=c("zscore"))

PLAGE <- gsva(MCL, T360, method=c("plage"))


#Make data frames of results for visualization


GSVA<- as.data.frame(GSVA)
GSVA_bio <- as.data.frame(GSVA_bio)
GSVA_kegg <- as.data.frame(GSVA_kegg)
GSVA_hallmark <- as.data.frame(GSVA_hallmark)

SSGSEA_MATCH <- as.data.frame(SSGSEA)
z_score_MATCH <- as.data.frame(z_score)
PLAGE_MATCH <- as.data.frame(PLAGE)

#Export pathway analysis results

write_tsv(GSVA, "GSVA.tsv")
write_tsv(GSVA_MATCH, "GSVA_MATCH.tsv")
write_tsv(PLAGE_MATCH, "PLAGE_MATCH")
write_tsv(z_score_MATCH, "Z-Score_MATCH")
write_tsv(SSGSEA_MATCH, "SSGSEA_MATCH.tsv")

```
#Visualize as heatmaps
```{r}
library(ComplexHeatmap)
library(pheatmap)
```
```{r}
annotations  <- rownames(GSVA)

MCL_ssGSEA <- pheatmap(SSGSEA_MATCH)
MCL_z_score <- pheatmap(z_score_MATCH)
MCL_plage <- pheatmap(PLAGE_MATCH)
MCL_hallmark <- pheatmap(GSVA_hallmark)

MCL_GSVA_M <- pheatmap(GSVA_MATCH)
MCL_GSVA<- pheatmap(GSVA)

#Run GSVA T360

MCL_exp <- gsva(MCL_exp, T360)
```

```{r}
#Differential gene expression analysis
library(DESeq2)
library(edgeR)
library(ggplot2)
library()
```
```{r}

```

```{r}
samples <- colnames(MCL_counts)
phenotype <- annotation_col$Phenotype
```
```{r}
#DEG at pathway level between responders and non responders
library(limma)

#Make expresion set for limma analysis and GSVA 

setwd("/Users/Holly/Desktop/MATCH_update")
Sample_Annotation <- read.table("Sample_Annotation.csv", sep=",", row.names = 1, header=TRUE)

metadata <- data.frame(labelDescription=
                         c("Sex","Tissue Type", "Phenotype","Histotype"),
                       row.names=c("Sex","Tissue","Phenotype","MCLType"))

phenoData <- new("AnnotatedDataFrame", data=annotation_col, varMetadata=metadata)

MCL_exp <- ExpressionSet(assayData=MCL_Genes, 
                         phenoData=phenoData)

```

```{r}
MCL <- MATCH_new_rawCountsWithAnnotations
MCL_counts<- as.matrix(data.frame(MCL[,-1:-4], row.names = MCL$Symbol))
MCL <- DGEList(MCL_counts)

MCL$samples$lib.size
cpm = cpm(MCL)
MCL$samples$norm.factors
MCL = calcNormFactors(MCL)

lcpm = cpm(MCL, log = TRUE)

L = mean(MCL$samples$lib.size)*1e-6

M = median(MCL$samples$lib.size)*1e-6

lcpm.cutoff = log2(10/M+2/L)
nsamples = ncol(MCL)
par(mfrow=c(1,2))
plot(density(lcpm[,1]), lwd = 2, ylim = c(0,0.26), las = 2, main="", xlab="")
title(main = "A. Expected Count", xlab = "Log-CPM")
abline(v = lcpm.cutoff, lty=3)

for (i in 2:nsamples){
 den = density(lcpm[,i])
 lines(den$x, den$y, lwd=2)
}

lcpm = cpm(MCL, log=TRUE)
plot(density(lcmp[,1]), lwd = 2, ylim = c(0,0.26), las = 2, main="", xlab="")
title(main = "B. Filtered Count", xlab = "Log-CPM")
abline(v = lcpm.cutoff, lty=3)

for (i in 2:nsamples){
 den = density(lcpm[,i])
 lines(den$x, den$y, lwd=2)
 
 MCL=calcNormFactors(MCL)
 
 MCL_norm <- cpm(MCL, log=TRUE, prior.count=3)}
```

```{r}
MCL <- MATCH_new_rawCountsWithAnnotations
MCL_counts<- as.matrix(data.frame(MCL[,-1:-4], row.names = MCL$Symbol))
MCL <- DGEList(counts=MCL_counts)

MCL <- calcNormFactors(MCL)

logCPM <- cpm(MCL, log=TRUE, prior.count=3)

fit <- lmFit(logCPM, mod)
fit <- eBayes(fit, trend=TRUE)
topTable(fit,coef=ncol(mod))
```

```{r}

MCL <- MATCH_new_normalizedCountsWithAnnotations

MCL_counts<- as.matrix(data.frame(MCL[,-1:-4], row.names = MCL$Symbol))

MCLfit <- lmFit(MCL_counts, mod)

fit <- eBayes(MCLfit)

res <- decideTests(fit, p.value=0.10)

summary(res)

tt <- topTable(fit, coef=2, n=Inf)
```

```{r}
mod <- model.matrix(~0 + phenotype)

colnames(mod) <- c("Nonresponder", "Responder")

contr.matrix=makeContrasts(RespondervsNon = Responder-Nonresponder, levels=colnames(mod))

MCLfit <- lmFit(v, mod)

fit <- eBayes(fit)
res <- decideTests(fit, p.value=0.10)
summary(res)

volcanoplot(fit,coef=2, )
```

```{r}
tt <- topTable(fit, coef=2, n=Inf)
DEpwys <- rownames(tt)[tt$adj.P.Val <= 0.10]
plot(tt$logFC, -log10(tt$P.Value), pch=".", cex=4, col=grey(0.75),
     main="", xlab="GSVA enrichment score difference Tumor 360 Pathways", ylab=expression(-log[10]~~Raw~P-value))
abline(h=-log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), col=grey(0.5), lwd=1, lty=2)
points(tt$logFC[match(DEpwys, rownames(tt))],
       -log10(tt$P.Value[match(DEpwys, rownames(tt))]), pch=".", cex=5, col="darkred")
text(max(tt$logFC)*0.85, -log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), "10% FDR", pos=3)
```

```{r}
DEpwys_es <- exprs(MCL_exp[DEpwys, ])
colorLegend <- c("darkred", "darkblue")
names(colorLegend) <- c("responder", "nonresponder")
sample.color.map <- colorLegend[pData(MCL_exp)[, "Phenotype"]]
names(sample.color.map) <- colnames(DEpwys_es)
sampleClustering <- hclust(as.dist(1-cor(DEpwys_es, method="spearman")),
                           method="complete")
geneSetClustering <- hclust(as.dist(1-cor(t(DEpwys_es), method="pearson")),
                            method="complete")
heatmap(DEpwys_es, ColSideColors=sample.color.map,
        margins=c(2, 20),
        labCol="", scale="row", Colv=as.dendrogram(sampleClustering),
        Rowv=as.dendrogram(geneSetClustering))
legend("topleft", names(colorLegend), fill=colorLegend, inset=-0.015, bg="white")
```

#Run GSVA T360

MCL_exp <- gsva(MCL_exp, T360)

```{r}
#Run GSVA with Custom Set
MCL_exp_custom <- gsva(MCL_Genes, Custom, min.sz=5)
```

```{r}
MCL_exp_custom <- ExpressionSet(assayData=MCL_exp_custom, 
                         phenoData=phenoData)

mod <- model.matrix(~ factor(MCL_exp_custom$Phenotype))
colnames(mod) <- c("ALL", "NOvsALL")
fit <- lmFit(MCL_exp_custom, mod)
fit <- eBayes(fit)
res <- decideTests(fit, p.value=0.10)
summary(res)
```

```{r}
tt <- topTable(fit, coef=2, n=Inf)

DEpwys <- rownames(tt)[tt$adj.P.Val <= 0.10]

plot(
  tt$logFC, -log10(tt$P.Value), pch=".", cex=4, col=grey(0.75),
  main="", xlab="GSVA enrichment score difference", ylab=expression(-log[10]~~Raw~P-value))
  abline(h=-log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), col=grey(0.5), lwd=1, lty=2)
  points(tt$logFC[match(DEpwys, rownames(tt))],
  -log10(tt$P.Value[match(DEpwys, rownames(tt))]), pch=".", cex=5, col="darkred")
  text(max(tt$logFC)*1.50, -log10(max(tt$P.Value[tt$adj.P.Val <= 0.05])), "5% FDR", pos=3)
```

```{r}
DEpwys_es <- exprs(MCL_exp_custom[DEpwys, ])
colorLegend <- c("darkred", "darkblue")
names(colorLegend) <- c("responder", "nonresponder")
sample.color.map <- colorLegend[pData(MCL_exp)[, "Phenotype"]]
names(sample.color.map) <- colnames(DEpwys_es)
sampleClustering <- hclust(as.dist(1-cor(DEpwys_es, method="spearman")),
                           method="complete")
geneSetClustering <- hclust(as.dist(1-cor(t(DEpwys_es), method="pearson")),
                            method="complete")
heatmap(DEpwys_es, ColSideColors=sample.color.map, xlab="samples",
        ylab="Pathways", margins=c(2, 20),
        labCol="", scale="row", Colv=as.dendrogram(sampleClustering),
        Rowv=as.dendrogram(geneSetClustering))
legend("topleft", names(colorLegend), fill=colorLegend, inset=0, bg="white")
```

```{r}
#With Hallmark genesets

hall <- getGmt("/Users/Holly/Downloads/h.all.v2023.1.Hs.symbols.gmt")
c2 <- getGmt("/Users/Holly/c2.all.v2023.1.Hs.symbols.gmt.txt")

MCL_exp <- gsva(MCL_exp, hall, min.sz=5)
```

```{r}
mod <- model.matrix(~ factor(MCL_exp$Phenotype))
colnames(mod) <- c("ALL", "NOvsALL")
fit <- lmFit(MCL_exp, mod)
fit <- eBayes(fit)
res <- decideTests(fit, p.value=0.10)
summary(res)
```

```{r}
tt <- topTable(fit, coef=2, n=Inf)
DEpwys <- rownames(tt)[tt$adj.P.Val <= 0.10]
plot(tt$logFC, -log10(tt$P.Value), pch=".", cex=4, col=grey(0.75),
     main="", xlab="GSVA enrichment score difference", ylab=expression(-log[10]~~Raw~P-value))
abline(h=-log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), col=grey(0.5), lwd=1, lty=2)
points(tt$logFC[match(DEpwys, rownames(tt))],
       -log10(tt$P.Value[match(DEpwys, rownames(tt))]), pch=".", cex=5, col="darkred")
text(max(tt$logFC)*0.85, -log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), "10% FDR", pos=3)
```

```{r}
MCL_DEG <- MATCH_new_responder_vs_non_responder_Date_1_

MCL_DEG<- as.matrix(data.frame(MCL_DEG[,2:21], row.names = MCL_DEG$upperSymbol))


DEpwys_es <- exprs(MCL_exp[DEpwys, ])
colorLegend <- c("darkred", "darkblue")

names(colorLegend) <- c("responder", "non_responder")
sample.color.map <- colorLegend[pData(MCL_exp)[, "Phenotype"]]
names(sample.color.map) <- colnames(DEpwys_es)
sampleClustering <- hclust(as.dist(1-cor(DEpwys_es, method="spearman")),
                           method="complete")
geneSetClustering <- hclust(as.dist(1-cor(t(DEpwys_es), method="pearson")),
                            method="complete")
heatmap(DEpwys_es, ColSideColors=sample.color.map,
        margins=c(2, 20),
        labCol="", scale="row", Colv=as.dendrogram(sampleClustering),
        Rowv=as.dendrogram(geneSetClustering))
legend("topleft", names(colorLegend), fill=colorLegend, inset=-0.01, bg="white")
```

```{r}
MCL_DEG <- MATCH_new_responder_vs_non_responder_Date_1_

MCL_DEG<- as.data.frame(data.frame(MCL_DEG[,-1:-4], row.names = MCL_DEG$Symbol))

EnhancedVolcano(MCL_DEG, lab=rownames(MCL_DEG), x="log2FoldChange", y="pvalue", pCutoff=10e-2, FCcutoff=1.5, pCutoffCol="padj", xlim=c(-4.0,4.0), ylim=c(0,-log10(10e-6)), labSize = 1.5, drawConnectors = T, boxedLabels = T, max.overlaps = Inf, title="Responders vs Non-Responders", subtitle = "to BTKi treatment")
```

#GSVA with Currated (KEGG, Biocarta, Wiki) pathways: Broad C2

```{r}

metadata <- data.frame(labelDescription=
                         c("Tissue Type", "Phenotype","Histotype"),
                       row.names=c("Tissue","Phenotype","MCLType"))

phenoData <- new("AnnotatedDataFrame", data=pheno_df, varMetadata=metadata)

MCL_exp <- ExpressionSet(assayData=MCL, 
                         phenoData=phenoData)


MCL_exp <- gsva(MCL_exp, c2, min.sz = 5)

```
```{r}
#For DEGs

MCL_exp <- ExpressionSet(assayData=MCL, 
                         phenoData=phenoData)

```

```{r}
mod <- model.matrix(~ factor(MCL_exp$Phenotype))
colnames(mod) <- c("ALL", "NOvsALL")
fit <- lmFit(MCL_exp, mod)
fit <- eBayes(fit)
res <- decideTests(fit, p.value=0.10)
summary(res)
```
```{r}
tt <- topTable(fit, coef=2, n=Inf)

DEpwys <- rownames(tt)[tt$adj.P.Val <= 0.10]
plot(tt$logFC, -log10(tt$P.Value), pch=".", cex=4, col=grey(0.75),
     main="", xlab="Differentially Expressed Genes", ylab=expression(-log[10]~~Raw~P-value))
abline(h=-log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), col=grey(0.5), lwd=1, lty=2)
points(tt$logFC[match(DEpwys, rownames(tt))],
       -log10(tt$P.Value[match(DEpwys, rownames(tt))]), pch=".", cex=5, col="darkred")
text(max(tt$logFC)*0.85, -log10(max(tt$P.Value[tt$adj.P.Val <= 0.10])), "10% FDR", pos=3)

EnhancedVolcano(tt,lab=rownames(tt), x="logFC", y="adj.P.Val", pCutoff = 0.10)
```

```{r}
DEpwys_es <- exprs(MCL_exp[DEpwys, ])

colorLegend <- c("darkred", "darkblue")

names(colorLegend) <- c("responder", "nonresponder")

sample.color.map <- colorLegend[pData(MCL_exp)[, "Phenotype"]]

names(sample.color.map) <- colnames(DEpwys_es)

sampleClustering <- hclust(as.dist(1-cor(DEpwys_es, method="spearman")),
                           method="complete")

geneSetClustering <- hclust(as.dist(1-cor(t(DEpwys_es), method="pearson")),
                            method="complete")

heatmap(DEpwys_es, ColSideColors=sample.color.map, xlab="samples",
        margins=c(2, 20),
        labCol="", scale="row", Colv=as.dendrogram(sampleClustering),
        Rowv=as.dendrogram(geneSetClustering))

legend("topleft", names(colorLegend), fill=colorLegend, inset=-0.01, bg="white")
```

#GSVA with ImmuneSigDB pathways
```{r}
DEG <- model.matrix(~factor(MCLexp$Phenotype))
colnames(DEG) <-c("all","respondervsnon")
fit <- lmFit(MCLexp, DEG)
fit <- eBayes(fit)
res <- decideTests(fit, p.value=0.10)
summary(res)


```

#Table for GSEA results
```{r}
library(gt)
library(gtExtras)
library(webshot)

MCL_MATCH_Tab <- MCL_MATCH %>% 
  gt() %>% 
  tab_header(title="Table 1: Patient Sample Attributes, GSEA Results, and Matched Therapies") %>% 
  fmt_number(columns=c(11,13,15,17,19,21)) %>% 
  cols_width('Patient ID' ~px (100)) %>% 
  cols_width((1:3) ~px (80), (4:9) ~px(100),contains("ES") ~px(80), everything() ~px (120)) %>% 
  cols_label(
    "T360 ES 1" = "ES 1",
    "T360 ES 2" = "ES 2",
    "T360 ES 3" = "ES 3"
  ) %>% 
  cols_align("left") %>% 
  gt_color_rows(c("ES 1","ES 2","ES 3","T360 ES 1","T360 ES 2","T360 ES 3"), palette = "ggsci::blue_material")


MCL_MATCH_Tab %>%  gtsave("Tab1.png", vwidth = 2500, vheight = 1600)

```

#Table 2

```{r}
MCL_MATCH_Tab2 <- Table_2_MATCH %>% 
  gt() %>% 
  tab_header(title="Table 2: Matched Therapies Used in In Vitro and In Vivo Screens") %>% 
  tab_footnote("R/R = relapsed or refractory") %>% 
  tab_footnote("AML = acute myeloid leukemia") %>% 
  tab_footnote("NHL = nonHodgkin Lymphoma") %>% 
  cols_align("left") %>% 
  opt_stylize(style = 2)
  
MCL_MATCH_Tab2 %>%  gtsave("Tab2.png", vwidth = 2500, vheight = 1600)
```

```{r}
#ESTIMATE algorithm
filtered <- filter_common_genes(MCL,
                                id="hgnc_symbol",
                                tidy=FALSE,
                                tell_missing=TRUE,
                                find_alias = TRUE)

scored <- estimate_score(filtered, is_affymetrix=TRUE)

plot_purity(scored, is_affymetrix = TRUE)
```

```{r}
library(enrichplot)
dotplot()
```

```{r}
#Pheno file 
pheno_df <- Sample_Annotation

pheno_df <- data.frame(pheno_df, row.names = pheno_df$`Sample Name`)

pheno_df <- data.frame(pheno_df[,-1, drop=FALSE])

rownames(pheno_df) <- colnames(MCL)


#Heatmap with normalized counts
pheatmap(MCL_normal, show_rownames = F, annotation_col = pheno_df, annotation_names_col = T)
```

```{r}
z_score <- function(x){
  (x-mean(x))/sd(x)
}

data_norm <- t(apply(MCL, 1, z_score))

annotation_col = data.frame(Sample_Annotation[4], row.names = Sample_Annotation$`Sample Name`)

rownames(annotation_col) = "Sample.Name"


pheatmap(data_norm, show_colnames = T, show_rownames = F, cluster_columns = F, annotation_col = annotation_col, annotation_colors = ann_colors)

pheatmap(MCL, show_colnames = T, show_rownames = F, cluster_cols = F, cluster_rows = F, annotation_col = annotation_col, annotation_colors = ann_colors, drop_levels = F, scale="row")

ann_colors = list(
  MCLType = c(Blastoid="blue",Classic="darkviolet",Pleomorphic="darkred" ),
  Phenotype=c(nonresponder="red",responder="darkgreen"),
  Tissue=c(Aphresis="lightblue",BM="darkorange",PB="tan",LN="grey",Other="yellow")
)

ann_colors = list(
  Phenotype=c(nonresponder="firebrick3",responder="darkgreen"))

my_col_order = c("MCL1","MCL2","MCL3","MCL4","MCL5","MCL6","MCL7","MCL8","MCL9","MCL10","MCL11","MCL12","MCL13","MCL14","MCL15","MCL16","MCL17","MCL18","MCL19","MCL20")

pheatmap(MCL[,my_col_order],show_colnames = T, show_rownames = F, cluster_cols = F, cluster_rows = F, annotation_col = annotation_col, annotation_colors = ann_colors, drop_levels = F, scale="row", annotation_names_col=F)

DEGs <-c("IL2RB","CTSW","CD247","GZMA","NKG7","STAT4","NCR1","GZMB","CD4","ITGB","XCL1/2","KEAP1","EOMES","CSF1R")

MCL_subset <- MCL[rownames(MCL) %in% DEGs,]

pheatmap(MCL_subset[,my_col_order],show_colnames = T, show_rownames = F, cluster_cols = F, cluster_rows = F, annotation_col = annotation_col, annotation_colors = ann_colors, drop_levels = F, scale="row", annotation_names_col=F)
```
