---
title: "Figure 2"
author: HA Hill
project: MCL MATCH
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r}
library(tidyverse)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(readxl)
```

```{r}
#Figure 2A
#Visualization of DEG using a volcano plot
#Read in Supplemental Table or R file "Gene_counts_Log_FC.rds"

Gene_counts <- read_xlsx("Supplemental_Table.xlsx")
```

```{r}
#We will visualize differences between non-responders compared to responders. 

Gene_counts$log2FoldChange_opposite <- (Gene_counts$log2FoldChange)*(-1)
```

```{r}
Gene_counts$pvalue <- as.numeric(Gene_counts$pvalue)

  e <- EnhancedVolcano(Gene_counts,
    lab = Gene_counts$upperSymbol,
    x = 'log2FoldChange',
    y = 'pvalue',
    title = 'Non Responders vs Responders',
    subtitle = "Differential Expression",
    pCutoff = 0.0114275,
    FCcutoff = 1,
   pointSize = 1.5,
    labSize = 3.0,
    labCol = 'black',
    labFace = 'bold',
    boxedLabels = FALSE,
    colAlpha = 4/5,
    legendPosition = 'right',
    legendLabSize = 10,
    legendIconSize = 3.0,
    drawConnectors = TRUE,
    widthConnectors = 0.5,
    colConnectors = 'black')
  
  plot <- e + ggplot2::coord_cartesian(xlim=c(-2.75, 2.75), ylim=c(0,5))
  
  plot
```

```{r}
pdf(file = "Volcano_NResp_Resp.pdf", height=9, width=9)

plot

dev.off()
```


```{r}
#Figure 2B
#Heatmap of DGES

MCL_mat <- read_excel("MCL_heatmap_DEG.xlsx")

anno <- MCL_hm %>% select(1:4)

MCL_mat <- MCL_mat %>% select(5:46)

MCL_mat_n <- MCL_mat %>% mutate_if(is.character,as.numeric)

MCL_mat_n <- scale(MCL_mat_n)

MCL_m <- t(MCL_mat_n) 
```

```{r}
BTKi = anno$Response
Sample = anno$Tissue
Time = anno$Time
Sex = anno$Sex
```

```{r}
ha = HeatmapAnnotation(BTKi=BTKi, Sample = Sample, Time=Time, Sex = Sex, col=list('BTKi'=c('Non-responder'= "darkblue",'Responder'="darkgreen"),
  'Sample'=c('Apheresis'="orange",'LN'="yellow",'BM'="blue",'PB'="red","Other"="gray"),
  'Sex'=c('Female'="pink",'Male'="lightblue"),
  'Time'=c('Naiive'="#67a9cf",'Relapsed'="violet","Treatment"="darkred")), which = "column", annotation_name_gp = gpar(fontsize = 8))
```


```{r}
pdf(file="DEG_heatmap_MCL.pdf", height=11, width=8)

set.seed(222)

heat <- Heatmap(MCL_m, heatmap_legend_param = list(title = "Expression"), top_annotation = ha, row_names_side = 'left', row_km = 4, row_names_gp = gpar(fontsize = 9, fontface = "italic"), column_names_gp = gpar(fontsize = 9), cluster_rows = T, cluster_columns = F, column_split = BTKi)

plot(heat)

dev.off()
```

